tasks.named('bootJar') {
    enabled = true
}

tasks.named('jar') {
    enabled = false
}

dependencies {
    implementation project(':domain')
    // 저장소 구현은 실행할 때만 필요하다. api 코드에서 storage를 import하면 컴파일 에러가 난다
    runtimeOnly project(':storage:db-core')

    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'

    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation testFixtures(project(':storage:db-core'))
}
